sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t net9876/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true net9876/docker-react npm run test
